ChatGptApiUrl: https://api.openai.com/v1
ChatGptModel: gpt-3.5-turbo
SessionExpirePeriod: 30m0s
SessionClearInterval: 1m0s
ServePort: 8080
MaxTaskQueueCap: 1024
Bots:
    /linebot:
        DefaultRole: 聊天機器人
CmdsTalkToAI:
    - "@ai"
    - "@小愛"
    - "@小爱"
CmdsClearSession:
    - /refresh
    - /clear
    - /clean
    - /清空
CmdsChangeRole:
    - /扮演
    - /cosplay
